<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use App\Models\Product;
class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'name' => 'Chongyun 8bit Controller',
                'details' => 'Immerse yourself in the pixelated world of Teyvat with the Chongyun Pixel Pro 8-bit Controller. This uniquely customized gaming accessory pays homage to the classic era of gaming while capturing the essence of Genshin Impact\'s frosty hero, Chongyun.',
                'description' => 'Game Controller',
                'category' => 'Tech and Gadgets',
                'image' => 'images/products/1.webp',
                'stock' => 49,
                'new_price' => 499,
                'old_price' => 1299,
                'featured' => 'Yes',
            ],
            [
                'name' => 'Sony Playstation PS5 Console',
                'details' => 'The PS5™ console unleashes new gaming possibilities that you never anticipated. Experience lightning fast loading with an ultra-high-speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio, and an all-new generation of incredible PlayStation® games. Harness the power of a custom CPU, GPU, and SSD with Integrated I/O that rewrite the rules of what a PlayStation® console can do.',
                'description' => 'Game Console',
                'category' => 'Tech and Gadgets',
                'image' => 'images/products/2.webp',
                'stock' => 0,
                'new_price' => 19999,
                'old_price' => 25000,
                'featured' => 'No',
            ],
            [
                'name' => 'XBOX Wireless Controller Gold Shadow',
                'details' => 'Elevate your gaming experience with the Xbox Wireless Controller Gold Shadow Edition. Immerse yourself in the sleek sophistication of its golden gradient design, casting a shadow that adds a touch of mystique to your gaming sessions. The textured grips ensure a comfortable and precise hold, while the wireless connectivity provides seamless control. With its striking aesthetics and advanced features, the Gold Shadow Edition transcends the ordinary, making every gaming moment a golden opportunity for victory.',
                'description' => 'Game Controller',
                'category' => 'Tech and Gadgets',
                'image' => 'images/products/3.webp',
                'stock' => 12,
                'new_price' => 1999,
                'old_price' => 2999,
                'featured' => 'No',
            ],
            [
                'name' => 'LOGITECH G304 LIGHTSPEED WIRELESS GAMING MOUSE',
                'details' => 'G304 is a LIGHTSPEED wireless gaming mouse designed for serious performance with latest technology innovations at an affordable price point. 12,000 DPI Performance, 10x Efficiency - HERO sensor is the next-gen optical gaming sensor from Logitech G that accomplishes both incredible performance and unprecedented efficiency. Because, in wireless gaming, there can be no compromises. Program DPI from 200 - 12,000 and save up to 5 profiles on the onboard memory.',
                'description' => 'Gaming Mouse',
                'category' => 'Tech and Gadgets',
                'image' => 'images/products/40.webp',
                'stock' => 0,
                'new_price' => 1199,
                'old_price' => 1500,
                'featured' => 'No',
            ],
            [
                'name' => 'RAZER VIPER MINI WIRED GAMING MOUSE',
                'details' => 'Experience hard-hitting performance with our lightest mouse ever created—a lean ultra-lightweight build that makes control effortless Featuring cutting-edge optical mouse switches a precise8 500 DPI sensor and Razer Speedflex Cable for supreme accuracy and speed. The #1 Best-Selling Gaming Peripherals Manufacturer in the US Source - The NPD Group U S Retail Tracking Service Keyboards Mice PC Headset/Pc Microphone Gaming Designed based on dollar sales Jan 2017- Dec 2019',
                'description' => 'Gaming Mouse',
                'category' => 'Tech and Gadgets',
                'image' => 'images/products/41.webp',
                'stock' => 2,
                'new_price' => 200,
                'old_price' => 170,
                'featured' => 'No',
            ],
            [
                'name' => 'Steam Deck 512GB NVME SSD',
                'details' => 'The Steam Deck sports a 7-inch 1280 x 800 LCD touchscreen that runs a refresh rate of 60Hz. Under the hood, it is equipped with a custom AMD APU processor, a Zen 2 CPU, an RDNA 2 GPU, has 16GB of LPDDR 5 RAM, and has storage options of 64GB eMMC, 256GB NVMe SSD, and 512GB NVMe SSD. All models include a high-speed microSD card slot for more storage. Furthermore, the Steam Deck runs on SteamOS 3.0 with Proton, a compatibility layer that makes it possible to run your games without any porting work needed from developers.',
                'description' => 'Handheld gaming computer',
                'category' => 'Tech and Gadgets',
                'image' => 'images/products/42.webp',
                'stock' => 99,
                'new_price' => 15499,
                'old_price' => 21999,
                'featured' => 'Yes',
            ],
            [
                'name' => 'Nintendo Switch',
                'details' => 'Play at home or on the go with one system The Nintendo Switch™ system is designed to go wherever you do, instantly transforming from a home console you play on TV to a portable system you can play anywhere. So you get more time to play the games you love, however you like.',
                'description' => 'Video game console',
                'category' => 'Tech and Gadgets',
                'image' => 'images/products/43.webp',
                'stock' => 12,
                'new_price' => 19999,
                'old_price' => 250000,
                'featured' => 'Yes',
            ],
            [
                'name' => 'Asus ROG Swift PG38UQ 38 inch 4K UHD 144HZ',
                'details' => 'ROG Swift PG38UQ 4K 144Hz gaming monitor ― 38-inch 4K UHD (3840 x 2160), 144Hz, 1ms, Fast IPS, G-Sync compatible, FreeSync Premium Pro, DisplayHDR™ 600, 98% DCI-P3, DisplayWidget Center, HDMI 2.1. 38-inch 4K UHD (3840 x 2160) gaming monitor with 144Hz refresh rate and Adaptive-Sync for super-smooth gaming visuals',
                'description' => 'Monitor',
                'category' => 'Tech and Gadgets',
                'image' => 'images/products/44.webp',
                'stock' => 1,
                'new_price' => 44000,
                'old_price' => 74999,
                'featured' => 'No',
            ],
            [
                'name' => 'Meta Quest 3 VR Headset',
                'details' => 'Step into mixed reality with the 512GB version of the Meta Quest 3 Advanced All-in-One VR Headset. The third gen PC-free headset combines VR with AR, using dual RGB cameras to provide full-color passthrough into your real world surroundings. This can be used to insert games, screens, and other virtual objects into your environment. When it comes to VR, the Quest 3 has been redesigned inside and out to deliver the best Quest experience yet. Graphics power is doubled with a new XR2 Gen 2 Snapdragon processor.',
                'description' => 'VR Headset',
                'category' => 'Tech and Gadgets',
                'image' => 'images/products/4.webp',
                'stock' => 2,
                'new_price' => 25000,
                'old_price' => 25999,
                'featured' => 'No',
            ],
            [
                'name' => 'Midnight Black PS5 Controller',
                'details' => 'Discover a deeper gaming experience1 with the innovative new PS5™ controller. The DualSense wireless controller for PS5 offers immersive haptic feedback2, dynamic adaptive triggers2 and a built-in microphone, all integrated into an iconic design.  Feel physically responsive feedback to your in-game actions with dual actuators which replace traditional rumble motors.',
                'description' => 'Game Controller',
                'category' => 'Tech and Gadgets',
                'image' => 'images/products/5.webp',
                'stock' => 0,
                'new_price' => 999,
                'old_price' => 2999,
                'featured' => 'No',
            ],
            [
                'name' => 'PS4 DUALSHOCK 4 WIRELESS CONTROLLER',
                'details' => 'Precision control: The feel, shape, and sensitivity of the Dualshock 4\'s analog sticks and trigger buttons have been enhanced to offer players absolute control for all games on PlayStation 4 Sharing at your fingertips: The addition of the share button makes sharing your greatest gaming moments as easy as a push of a button. New ways to play: Revolutionary features like the touch pad, integrated light bar, and built in speaker offer exciting new ways to experience and interact with your games',
                'description' => 'Game Controller',
                'category' => 'Tech and Gadgets',
                'image' => 'images/products/6.webp',
                'stock' => 10,
                'new_price' => 30000,
                'old_price' => 23000,
                'featured' => 'Yes',
            ],
            [
                'name' => 'GAN 356 M 3x3 Magnetic Speed Cube',
                'details' => 'Have you ever craved a GAN cube with the latest mechanism but just a portion cost of flagship? Now you\'ve found it - GAN 356 M, with a plastic core, new GES design, visible magnets, anti-scratch surface and a lot more features at a mid-range price. It\'s the modern cube that really hits the spot!',
                'description' => 'Speed cube',
                'category' => 'Toys and Games',
                'image' => 'images/products/31.webp',
                'stock' => 99,
                'new_price' => 899,
                'old_price' => 1199,
                'featured' => 'No',
            ],
            [
                'name' => 'Crocodile Teeth Dentist Game',
                'details' => 'Crocodile Teeth Dentist Game - ABS Crocodile Biting Finger Games, Hand Pulling Teeth Classic Toy, Family Tabletop Party Kids Toy, Portable Funny Gags Toy with Keychain for Kids & Adults. The finger-biting toys designed by cartoon toys make the game very interesting. Toys come with key chains, which can be used as ornaments for key chains.',
                'description' => 'Toy',
                'category' => 'Toys and Games',
                'image' => 'images/products/34.webp',
                'stock' => 0,
                'new_price' => 99,
                'old_price' => 120,
                'featured' => 'No',
            ],
            [
                'name' => 'Fast and Furious Die-cast vehicle',
                'details' => 'Jada Toys presents a new series of authentically detailed vehicles from the Fast & Furious franchise! This 1:24th scale vehicle measures approximately 8 inches long. Made of detailed die-cast metal with plastic construction, this amazing replica features opening doors and hood and real rolling wheels! Officially licensed, collect them all!',
                'description' => 'Toy Car',
                'category' => 'Toys and Games',
                'image' => 'images/products/10.webp',
                'stock' => 7,
                'new_price' => 100,
                'old_price' => 120,
                'featured' => 'No',
            ],
            [
                'name' => 'Quick Push Console with Instant Sound Feedback',
                'details' => 'Our handheld game console, the Speed Push Pop, offers four fun game modes - stage mode, memory mode, scoring mode, and multiplayer mode. Each mode provides a unique way to play and enjoy the game, and the console\'s unique shape design makes it an excellent puzzle game and decompression tool for both children and adults.',
                'description' => 'Toy',
                'category' => 'Toys and Games',
                'image' => 'images/products/37.webp',
                'stock' => 0,
                'new_price' => 200,
                'old_price' => 170,
                'featured' => 'No',
            ],
            [
                'name' => 'BEE AND PUPPYCAT',
                'details' => 'Adulting is hard when you\'ve got bills to pay. While temp-work may not sound like much, things can get wild when you\'re traveling between dimensions. Wherever your quests take you, PuppyCat will be there to accompany you as this fun plush toy companion. Crafted with the utmost care and attention to detail, this soft character plushie will make your journey through Fishbowl Space extraordinary.',
                'description' => 'Cute Plushie',
                'category' => 'Toys and Games',
                'image' => 'images/products/7.webp',
                'stock' => 5,
                'new_price' => 100,
                'old_price' => 120,
                'featured' => 'No',
            ],
            [
                'name' => 'PUSHEEN THE CAT',
                'details' => 'A fellow student has seemingly vanished from the famous School of Witchcraft and Wizardry - and it is up to you to solve the mysterious disappearance. Playing as Harry, Ron, Hermione, Ginny, Luna or Neville, you must try and discover WHO did it, WHAT spell or item they used and WHERE the student was attacked. Move around Hogwarts making suggestions. But watch out! Wheels on the board will keep changing revealing secret passages, moving staircases or even the Dark Mark! Protection from the Dark Mark comes from the spells, allies and items provided by the Help Cards.',
                'description' => 'Board Game',
                'category' => 'Toys and Games',
                'image' => 'images/products/9.webp',
                'stock' => 3,
                'new_price' => 150,
                'old_price' => 180,
                'featured' => 'No',
            ],
            [
                'name' => 'Spongebob Plushie',
                'details' => 'Show off your love of Nickelodeon\'s SpongeBob SquarePants with this fun character plush! These 10-inch tall SpongeBob plush collectibles are sure to please fans of the popular animated series with their soft construction and absolutely adorable design. Collect them all! Officially licensed SpongeBob SquarePants plush collectible. Produced by Johnny\'s Toys.',
                'description' => 'Plushie',
                'category' => 'Toys and Games',
                'image' => 'images/products/11.webp',
                'stock' => 12,
                'new_price' => 45,
                'old_price' => 60,
                'featured' => 'Yes',
            ],
            [
                'name' => 'Patrick Star Plushie',
                'details' => 'Show off your love of Nickelodeon\'s SpongeBob SquarePants with this fun character plush! These SpongeBob plush are sure to please fans of the animated series with their soft construction and adorable design. Officially licensed. Produced by Chucks Toys.',
                'description' => 'Plushie',
                'category' => 'Toys and Games',
                'image' => 'images/products/12.webp',
                'stock' => 4,
                'new_price' => 190,
                'old_price' => 220,
                'featured' => 'Yes',
            ],
            [
                'name' => 'WE BARE BEARS GRIZZ',
                'details' => 'GUND is proud to present plush toys based on We Bare Bears, the hit Cartoon Network comedy about three brother bears and their adventures! This 12" plush version of Grizz features accurate details sure to please fans of the show. All three We Bare Bears (each sold separately) are stackable for easy display and added play value! As always, high-quality and huggable plush ensures this product will remain a favorite for years to come. Surface-washable for easy cleaning. Appropriate for ages one and up.',
                'description' => 'Plushie',
                'category' => 'Toys and Games',
                'image' => 'images/products/13.webp',
                'stock' => 4,
                'new_price' => 190,
                'old_price' => 220,
                'featured' => 'No',
            ],
            [
                'name' => 'WE BARE BEARS ICE BEAR',
                'details' => 'GUND is proud to present plush toys based on We Bare Bears, the hit Cartoon Network comedy about three brother bears and their adventures! This 12" plush version of Ice Bear features accurate details sure to please fans of the show. All three We Bare Bears (each sold separately) are stackable for easy display and added play value! As always, high-quality and huggable plush ensures this product will remain a favorite for years to come. Surface-washable for easy cleaning. Appropriate for ages one and up.',
                'description' => 'Plushie',
                'category' => 'Toys and Games',
                'image' => 'images/products/14.webp',
                'stock' => 4,
                'new_price' => 190,
                'old_price' => 220,
                'featured' => 'No',
            ],
            [
                'name' => 'WORLD OF HARRY POTTER',
                'details' => 'Relive the magic of seeing Hogwarts School of Witchcraft and Wizardry for the first time while putting together this Harry Potter puzzle. Full-color puzzle shows Hogwarts castle at night. 550-piece puzzle measures 18" x 24" when fully assembled. A perfect gift for Harry Potter fans!',
                'description' => '550-PIECE PUZZLE',
                'category' => 'Toys and Games',
                'image' => 'images/products/8.webp',
                'stock' => 8,
                'new_price' => 75,
                'old_price' => 90,
                'featured' => 'No',
            ],
            [
                'name' => 'Hasbro Gaming Jenga Wooden Blocks Stacking',
                'details' => 'BLOCK BALANCING GAME: Pull out a block, place it on top, but don\'t let the tower fall. This fun, challenging game is a great game for families and kids 6 and up. GAME FOR 1 OR MORE PLAYERS: No friends around. No problem. Play Jenga solo. Practice stacking skills, building the tower and trying not to let it come tumbling down',
                'description' => 'Game',
                'category' => 'Toys and Games',
                'image' => 'images/products/35.webp',
                'stock' => 0,
                'new_price' => 200,
                'old_price' => 279,
                'featured' => 'No',
            ],
            [
                'name' => 'Dancing Cactus Talking Toy',
                'details' => 'LED Color flashing light Cactus Toys: You can use it as a bedside lamp to accompany you to sleep. Knitted plush made, soft material, comfortable, safe. This product uses non-toxic and harmless plush fabric which is soft and comfortable for kids to play with confidence. Wipe off the dust with a damp cloth for cleanup',
                'description' => 'Toy',
                'category' => 'Toys and Games',
                'image' => 'images/products/36.webp',
                'stock' => 0,
                'new_price' => 200,
                'old_price' => 170,
                'featured' => 'No',
            ],
            [
                'name' => 'Starry Night',
                'details' => 'Get a hand-painted museum-quality Reproduction of "Starry Night" by Vincent Van Gogh. The Reproduction will be hand-painted by one of our talented artists. "Starry Night" by Vincent Van Gogh Reproduction will come with a Free Certificate of Authenticity that verifies the authenticity of the hand-painted fine art reproduction you purchased.',
                'description' => 'Painting',
                'category' => 'Artworks',
                'image' => 'images/products/15.webp',
                'stock' => 1,
                'new_price' => 5190,
                'old_price' => 8220,
                'featured' => 'No',
            ],
            [
                'name' => 'Mona Lisa',
                'details' => 'Get a hand-painted museum-quality Reproduction of "Mona Lisa (La Gioconda) c. 1503-05" by Leonardo Da Vinci. The Reproduction will be hand-painted by one of our talented artists. "Mona Lisa (La Gioconda) c. 1503-05" by Leonardo Da Vinci Reproduction will come with a Free Certificate of Authenticity that verifies the authenticity of the hand-painted fine art reproduction you purchased.',
                'description' => 'Painting',
                'category' => 'Artworks',
                'image' => 'images/products/16.webp',
                'stock' => 1,
                'new_price' => 3190,
                'old_price' => 12220,
                'featured' => 'No',
            ],
            [
                'name' => 'Christ In The Storm On The Sea Of Galilee',
                'details' => 'Get a hand-painted museum-quality Reproduction of "Christ In The Storm On The Sea Of Galilee" by Rembrandt van Rijn" by Rembrandt Van Rijn. The Reproduction will be hand-painted by one of our talented artists. "Christ In The Storm On The Sea Of Galilee" by Rembrandt van Rijn" by Rembrandt Van Rijn Reproduction will come with a Free Certificate of Authenticity that verifies the authenticity of the hand-painted fine art reproduction you purchased.',
                'description' => 'Painting',
                'category' => 'Artworks',
                'image' => 'images/products/17.webp',
                'stock' => 1,
                'new_price' => 3190,
                'old_price' => 4220,
                'featured' => 'No',
            ],
            [
                'name' => 'The Wanderer above the Mists',
                'details' => 'Get a hand-painted museum-quality Reproduction of "The Wanderer above the Mists 1817-18" by Caspar David Friedrich. The Reproduction will be hand-painted by one of our talented artists. "The Wanderer above the Mists 1817-18" by Caspar David Friedrich Reproduction will come with a Free Certificate of Authenticity that verifies the authenticity of the hand-painted fine art reproduction you purchased.',
                'description' => 'Painting',
                'category' => 'Artworks',
                'image' => 'images/products/18.webp',
                'stock' => 1,
                'new_price' => 2190,
                'old_price' => 3220,
                'featured' => 'No',
            ],
            [
                'name' => 'Branches with Almond Blossom',
                'details' => 'Get a hand-painted museum-quality Reproduction of "Branches with Almond Blossom" by Vincent Van Gogh. The Reproduction will be hand-painted by one of our talented artists. "Branches with Almond Blossom" by Vincent Van Gogh Reproduction will come with a Free Certificate of Authenticity that verifies the authenticity of the hand-painted fine art reproduction you purchased.',
                'description' => 'Painting',
                'category' => 'Artworks',
                'image' => 'images/products/19.webp',
                'stock' => 4,
                'new_price' => 1090,
                'old_price' => 11999,
                'featured' => 'No',
            ],
            [
                'name' => 'The Scream',
                'details' => 'Get a hand-painted museum-quality Reproduction of "The Scream" by Edvard Munch. The Reproduction will be hand-painted by one of our talented artists. "The Scream" by Edvard Munch Reproduction will come with a Free Certificate of Authenticity that verifies the authenticity of the hand-painted fine art reproduction you purchased.',
                'description' => 'Painting',
                'category' => 'Artworks',
                'image' => 'images/products/20.webp',
                'stock' => 4,
                'new_price' => 990,
                'old_price' => 1500,
                'featured' => 'No',
            ],
            [
                'name' => 'CARTMAN BRAH',
                'details' => 'Embrace the irreverent charm of South Park with the Cartman Brah Youtooz collectible. This figure captures Cartman in his iconic pose, complete with cheeky expression and distinctive hand gesture. Add a touch of animated mischief to your collection with this unique and humor-filled collectible.',
                'description' => 'Youtooz',
                'category' => 'Collectibles',
                'image' => 'images/products/21.webp',
                'stock' => 4,
                'new_price' => 190,
                'old_price' => 220,
                'featured' => 'No',
            ],
            [
                'name' => 'GOOD TIMES WITH WEAPONS KYLE',
                'details' => 'Bring the South Park universe to life with the Weapons Kyle Youtooz collectible. This figure showcases Kyle wielding an array of weapons, capturing the essence of his adventurous spirit. Immerse yourself in the animated world of South Park and showcase your fandom with this detailed and dynamic Youtooz figure.',
                'description' => 'Youtooz',
                'category' => 'Collectibles',
                'image' => 'images/products/22.webp',
                'stock' => 8,
                'new_price' => 180,
                'old_price' => 210,
                'featured' => 'No',
            ],
            [
                'name' => 'GOOD TIMES WITH WEAPONS STAN',
                'details' => 'Complete your South Park Youtooz collection with the Weapons Stan figure. This collectible captures Stan armed and ready for mischief, showcasing his determined and adventurous personality. Whether you\'re a South Park fan or a collector of unique figures, Weapons Stan is a must-have addition to your display.',
                'description' => 'Youtooz',
                'category' => 'Collectibles',
                'image' => 'images/products/23.webp',
                'stock' => 12,
                'new_price' => 250,
                'old_price' => 220,
                'featured' => 'No',
            ],
            [
                'name' => 'PAJAMA CARTMAN',
                'details' => 'Step into the whimsical world of South Park with the Pajama Cartman Youtooz collectible. This figure features Cartman in cozy pajamas, capturing a playful and endearing moment from the animated series. Enhance your collection with this delightful and humorous representation of one of South Park\'s most iconic characters.',
                'description' => 'Youtooz',
                'category' => 'Collectibles',
                'image' => 'images/products/24.webp',
                'stock' => 15,
                'new_price' => 130,
                'old_price' => 160,
                'featured' => 'No',
            ],
            [
                'name' => 'CARTMAN WITH IMPLANTS',
                'details' => 'Bring laughter to your collection with the Cartman With Implants Youtooz figure. This collectible captures Cartman in a memorable moment featuring his distinctive "implants." Add a touch of humor and irreverence to your display with this unique South Park Youtooz collectible.',
                'description' => 'Youtooz',
                'category' => 'Collectibles',
                'image' => 'images/products/25.webp',
                'stock' => 6,
                'new_price' => 190,
                'old_price' => 170,
                'featured' => 'No',
            ],
            [
                'name' => 'NAIL ON HEAD PATRICK',
                'details' => 'Dive into the absurdity of SpongeBob SquarePants with the Nail on Head Patrick Youtooz figure. This collectible captures Patrick with a nail on his head, showcasing the humor and charm of the beloved character. Whether you\'re a SpongeBob fan or a collector of quirky figures, Nail on Head Patrick is a standout addition to any collection.',
                'description' => 'Youtooz',
                'category' => 'Collectibles',
                'image' => 'images/products/26.webp',
                'stock' => 10,
                'new_price' => 120,
                'old_price' => 150,
                'featured' => 'No',
            ],
            [
                'name' => 'IronMouse Plushie',
                'details' => 'Snuggle up with the IronMouse Plushie, a must-have for fans of virtual YouTubers. This adorable plushie features IronMouse in a huggable form, perfect for bringing a touch of virtual entertainment to your everyday life. Whether displayed on your shelf or used as a cuddly companion, the IronMouse Plushie is a delightful addition to any collection.',
                'description' => 'Plushie',
                'category' => 'Collectibles',
                'image' => 'images/products/27.webp',
                'stock' => 20,
                'new_price' => 180,
                'old_price' => 210,
                'featured' => 'Yes',
            ],
            [
                'name' => 'Avatar Appa',
                'details' => 'Embark on an adventure with the Avatar Appa plushie. This lovable plushie brings the magic of the animated series to life, featuring Appa, the iconic flying bison. Whether you\'re a fan of Avatar: The Last Airbender or simply adore adorable plushies, the Avatar Appa plushie is a charming addition to your collection.',
                'description' => 'Plushie',
                'category' => 'Collectibles',
                'image' => 'images/products/28.webp',
                'stock' => 5,
                'new_price' => 270,
                'old_price' => 340,
                'featured' => 'Yes',
            ],
            [
                'name' => 'Avatar Toph',
                'details' => 'Add a touch of Earthbending mastery to your collection with the Avatar Toph plushie. This plushie captures Toph Beifong, the iconic and feisty character from Avatar: The Last Airbender. Whether displayed on your shelf or used as a cuddly companion, the Avatar Toph plushie is a delightful addition for fans of the beloved animated series.',
                'description' => 'Plushie',
                'category' => 'Collectibles',
                'image' => 'images/products/29.webp',
                'stock' => 18,
                'new_price' => 150,
                'old_price' => 180,
                'featured' => 'No',
            ],
            [
                'name' => 'Spy x Family Bond',
                'details' => 'Immerse yourself in the world of "Spy x Family" with the Bond Figurine. This collectible captures a unique and heartwarming family bond from the popular manga series. Whether you\'re a manga enthusiast or a collector of figurines, the Spy x Family Bond Figurine is a captivating addition to your display, showcasing the intrigue and emotion of the series.',
                'description' => 'Figurine',
                'category' => 'Collectibles',
                'image' => 'images/products/30.webp',
                'stock' => 0,
                'new_price' => 200,
                'old_price' => 370,
                'featured' => 'No',
            ],
            [
                'name' => 'BUNINI COSTUME PLUSH (PINK)',
                'details' => 'Experience unique identity now in your daily life. We\'ve lovingly recreated the adorable bunini featured in the "ASAP" music video as a charming plush. The costumes are detachable, allowing you to collect a variety of costumes & personalize your bunini to create a truly one-of-kind character.',
                'description' => 'Mellolilly',
                'category' => 'Collectibles',
                'image' => 'images/products/32.webp',
                'stock' => 99,
                'new_price' => 1500,
                'old_price' => 2000,
                'featured' => 'No',
            ],
            [
                'name' => 'BUNINI COSTUME PLUSH (Yellow)',
                'details' => 'Experience unique identity now in your daily life. We\'ve lovingly recreated the adorable bunini featured in the "ASAP" music video as a charming plush. The costumes are detachable, allowing you to collect a variety of costumes & personalize your bunini to create a truly one-of-kind character.',
                'description' => 'Mingtz',
                'category' => 'Collectibles',
                'image' => 'images/products/33.webp',
                'stock' => 99,
                'new_price' => 1500,
                'old_price' => 2000,
                'featured' => 'No',
            ],
            [
                'name' => 'Pokemon Trading Card Game Pokemon Go',
                'details' => 'A special set for the Pokémon TCG trading card game will focus on the popular mobile game Pokémon GO! Go hunting again and collect all the cards that you get only and only in the special products of this set (booster packs are not sold separately). Get into battle with this Elite Trainer Box!',
                'description' => 'TCG',
                'category' => 'Collectibles',
                'image' => 'images/products/38.webp',
                'stock' => 0,
                'new_price' => 2999,
                'old_price' => 3000,
                'featured' => 'No',
            ],
            [
                'name' => 'POKEMON TRADING CARD GAME SS4 MINI PORTFOLIO',
                'details' => 'About the size of a Pokémon TCG card, mini portfolios are a compact, convenient way to store and display up to 60 cards from your collection. This one features dynamic artwork of Gigantamax Pikachu and Gigantamax Orbeetle, and it comes with a Sword & Shield—Vivid Voltage booster pack to get you started!',
                'description' => 'TCG',
                'category' => 'Collectibles',
                'image' => 'images/products/39.webp',
                'stock' => 50,
                'new_price' => 350,
                'old_price' => 490,
                'featured' => 'No',
            ],
            
            
        ];

        foreach ($products as $productData) {
            $productData['slug'] = Str::slug($productData['name']);
            Product::create($productData);
        }
    }
}